vim.keymap.set("n", "<leader>e", vim.cmd.Ex)
vim.keymap.set("i", "<leader>jk", "<Esc>")
vim.keymap.set("n", "<leader>q", vim.cmd.q)
vim.keymap.set("n", "<leader>w", vim.cmd.w)
local tel = require('telescope.builtin')
vim.keymap.set("n", "<leader>ff", tel.find_files)
vim.keymap.set("n", "<leader>fw", tel.live_grep)
vim.keymap.set("n", "<leader>ft", tel.colorscheme)
vim.keymap.set("n", "<leader>fb", tel.buffers)
